version: '3.1'

services:

  backend:
    depends_on:
      - mysql57
    build: .
    ports:
      - "3001:3001"
    networks:
      - bco_default
    restart: always

  mysql57:
    image: mysql:5.7
    container_name: mysql57
    networks:
      - bco_default
    ports:
      - "0.0.0.0:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123#@!
      MYSQL_DATABASE: testepicpay
    restart: always
    volumes:
      - ./.mysql-data/db:/var/lib/mysql

networks:
  bco_default:
    external: true